apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: health-999-staging

images:
- digest: sha256:588db84a083746453972264733ff5f9f16cd9663595fb421115e251b3baded02
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: image-registry.openshift-image-registry.svc:5000/health-999-develop/health-999-record
